### ISSUE TITLE
Openpose maxes out exactly at 10.0fps both with/without tracking. [Ubuntu 16.04]

### ISSUE THREAD

**Issue by Harsharma2308** [CMU-Perceptual-Computing-Lab/openpose#1093] opened 2019-02-19 04:08 UTC
### Issue Summary
It is very interesting that whatever parameters I run while executing openpose, the algorithm maxes out at 10.0 fps. What is strange is the fact that it is almost exactly 10.0 fps and doesn't fluctuate at all more than +/- 0.1 fps. 
On running 
`./build/examples/openpose/openpose.bin` ,the fps is 10.0

And even on running
`./build/examples/openpose/openpose.bin --tracking 20`
the algorithm runs at 10.0 fps.

Has anyone faced this issue or does anyone have any insights to what might be happening?

### Executed Command (if any)
`./build/examples/openpose/openpose.bin`

### Type of Issue
- Help wanted

### Your System Configuration
2. **OpenPose version**: Commit 0872e9b4ced4a94aa78007aef4ad5f0a88c14dc5 ; (December 18 2018)

3. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** (`lsb_release -a` in Ubuntu): Ubuntu 16.04
    - **Release or Debug mode**? (by default: release): Default
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no): No
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: commit f019d0dfe86f49d1140961f8c7dec22130c83154 (July 12 2016)
    - **CMake version** (`cmake --version` in Ubuntu): 3.5.1
    - **OpenCV version**: 3.3.1

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
    - **cuDNN version**: 6.0.21
    - **GPU model** (`nvidia-smi` in Ubuntu): GTX Nvidia 1080; Driver Version: 384.130

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#profiling-speed).

```
98.359735 msec at in /home/harsh/sof/openpose/include/openpose/producer/wDatumProducer.hpp:workProducer():78

0.000253 msec at in /home/harsh/sof/openpose/include/openpose/thread/wIdGenerator.hpp:work():76

0.001213 msec at in /home/harsh/sof/openpose/include/openpose/core/wScaleAndSizeExtractor.hpp:work():74

0.832438 msec at in /home/harsh/sof/openpose/include/openpose/core/wCvMatToOpInput.hpp:work():71

0.607721 msec at in /home/harsh/sof/openpose/include/openpose/core/wCvMatToOpOutput.hpp:work():73

52.139500 msec at in /home/harsh/sof/openpose/include/openpose/pose/wPoseExtractor.hpp:work():98

2.695060 msec at in /home/harsh/sof/openpose/include/openpose/pose/wPoseRenderer.hpp:work():79

0.535896 msec at in /home/harsh/sof/openpose/include/openpose/core/wOpOutputToCvMat.hpp:work():69

0.257776 msec at in /home/harsh/sof/openpose/include/openpose/gui/wGuiInfoAdder.hpp:work():72

5.677956 msec at in /home/harsh/sof/openpose/include/openpose/gui/wGui.hpp:workConsumer():87

```

**Comment by gineshidalgo99** [comment] 2019-02-19 04:10
Thanks for point 7, it def. help a lot! The problem is your webcam. Either OpenCV does not have appropiate codecs to read faster, or your webcam can only run at that speed. Check if you can get higher speed than 10FPS when reading the webcam (some free online webcam displayers online).

**Comment by Harsharma2308** [comment] 2019-02-19 20:22
If I run rospackage [usb_cam](http://wiki.ros.org/usb_cam) , the ros topic usb_cam publishes at almost 30Hz(29.99). So the camera does seem to stream images at 30.0FPS.

**Comment by gineshidalgo99** [comment] 2019-02-19 23:10
Then it is an OpenCV problem. You did not compile it with the right webcam codecs. Re-compile OpenCV with the right camera codecs (or use the default sudo apt-get one that we recommend in the doc/). This is no longer an OpenPose issue, so I will close it. Best

**Closed by gineshidalgo99** 2019-02-19 23:10 UTC
Labels: help wanted/question

**Comment by Harsharma2308** [comment] 2019-02-21 20:51
I guess you are right. 
Just adding to that, if I run from a video ,
Without tracking-
` ./build/examples/openpose/openpose.bin  --video ~/Videos/knife_calibrate2.mp4`
 The algorithm runs at 16.5fps.
With tracking-
` ./build/examples/openpose/openpose.bin  --video ~/Videos/knife_calibrate2.mp4 --tracking 2 --number_people_max 1
`
The algorithm does run at 40FPS.
On running from the webcam only, the  algorithm runs slower.

**Comment by djramakrishna** [comment] 2021-02-01 10:43
@Harsharma2308 Hi ! Are you using BODY25 model or the COCO ?
