### ISSUE TITLE
VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.

### ISSUE THREAD

**Issue by CuiYiZe** [CMU-Perceptual-Computing-Lab/openpose#41] opened 2017-05-25 05:25 UTC
### Issue summary
VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.

### Executed command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi

### OpenPose output (if any)
Starting pose estimation demo.
Unable to stop the stream: Inappropriate ioctl for device
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Error:
VideoCapture (video) could not be opened for path: 'examples/media/video.avi'.

Coming from:
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():33
- src/openpose/producer/videoCaptureReader.cpp:VideoCaptureReader():37

Aborted (core dumped)

### Type of issue
im sure ihave the video.avi in the media document. And i follow your installation.md to set the openpose 

### Your system configuration
**Operating system** (`lsb_release -a` on Ubuntu): Ubuntu16.04
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 8.0
**cuDNN version**:
**GPU model** (`nvidia-smi`): 
**Caffe version**: Default from OpenPose or custom version.
**OpenCV version**: installed with `apt-get install libopencv-dev` or OpenCV 2.X or OpenCV 3.X. 3.0
Compiler (`gcc --version` on Ubuntu):

**Comment by gineshidalgo99** [comment] 2017-05-25 16:21
Does `./build/examples/openpose/rtpose.bin --image_dir examples/media/` works for you? If it does not either, check #17.

In addition, does the webcam works? `./build/examples/openpose/rtpose.bin`

And finally, what is your OpenCV version?

**Comment by CuiYiZe** [comment] 2017-05-26 01:40
thx for your reply. While i can run the image demo ./build/examples/openpose/openpose.bin --image_dir examples/media/
But i cant run the video and webcam demo 
And i use the opencv3.1 and i have change the Makefile.config as your installation.md says

**Comment by CuiYiZe** [comment] 2017-05-26 07:06
thx for your help 
i have solve this problem 
i rebuild the Opencv3.1 and i can run the video demo

**Comment by CuiYiZe** [comment] 2017-05-26 08:06
By the way  the video demo is so slow which only 1.5fps so im trying to find how to speed it up

**Comment by gineshidalgo99** [comment] 2017-05-26 14:16
Great, closing this.

(Please, different questions on different issue threads so people can find them. For speed, check #43 )

**Closed by gineshidalgo99** 2017-05-26 14:16 UTC
Labels: help wanted

**Comment by Ayehsu** [comment] 2017-07-18 12:12
I want to know how to save the video file as frame images similar with the keypoint jason file.

**Comment by gineshidalgo99** [comment] 2017-07-18 12:31
Check the doc for that

**Comment by BrettLL** [comment] 2017-11-03 02:48
@CuiYiZe hi, I met the same problem and think it is a opencv problem. The problem is 'Unable to stop the stream: Inappropriate ioctl for device'. You said you had rebuilt Opencv3.1, could you tell how to rebuild opencv and get success? I build opencv several times and it occurs the same problem, thank you ~

**Comment by CuiYiZe** [comment] 2017-11-09 07:04
IM sorry for reading your email too late ,i have no longer to run the Openpose. So maybe you can try to delete the origin Opencv and maybe make the Opencv path correct and use some  video demo to test the Opencv whether Ok or NOT





------------------ 原始邮件 ------------------
发件人: "BrettLL";<notifications@github.com>;
发送时间: 2017年11月3日(星期五) 上午10:48
收件人: "CMU-Perceptual-Computing-Lab/openpose"<openpose@noreply.github.com>;
抄送: "崔益泽。"<835486111@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [CMU-Perceptual-Computing-Lab/openpose] VideoCapture (video)could not be opened for path: 'examples/media/video.avi'. (#41)




@CuiYiZe hi, I met the same problem and think it is a opencv problem. The problem is 'Unable to stop the stream: Inappropriate ioctl for device'. You said you had rebuilt Opencv3.1, could you tell how to rebuild opencv and get success? I build opencv several times and it occurs the same problem, thank you ~

**Comment by BrettLL** [comment] 2017-11-09 07:38
@CuiYiZe thanks  I think it's opencv problem~~

**Comment by Mohsan1995** [comment] 2018-03-02 11:33
Hi,

For me the video.avi works, but when I try an other video I have this issue : 
'VideoCapture (video) could not be opened for path: ..'

I try many video .mp4, .avi but none work (only the video.avi of exemple).

**Comment by gineshidalgo99** [comment] 2018-03-03 15:42
Please, show me your whole command and a link to a video that didn't work.

**Comment by blmhds** [comment] 2019-03-15 12:31
Starting OpenPose demo...
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:578)

Error:
VideoCapture (IP camera/video) could not be opened for path: 'examples\media\video.avi'. If it is a video path, is the path correct?

I installed openpose-master on windows10,but evertime I start it with command ,the errors was pushed on the dos screen,so I need one of your help,thx!

**Comment by gineshidalgo99** [comment] 2019-03-15 12:52
Please, add your system configuration as the GitHub issue template specifies

**Comment by CuiYiZe** [comment] 2023-05-16 07:56
谢谢亲。我一定仔细查看。有事加微信，微信号 AyuLLj
