### ISSUE TITLE
openpose-1.3.0-win64-cpu-binaries is error：Cublas won't be available.

### ISSUE THREAD

**Issue by nanako-ut** [CMU-Perceptual-Computing-Lab/openpose#550] opened 2018-04-23 12:26 UTC
I use openpose-1.3.0-win64-cpu-binaries.zip

when I run exe, it's error.

openpose-1.3.0-win64-cpu-binaries> bin/OpenPoseDemo.exe --video examples/media/video.avi
Starting pose estimation demo.
Starting thread(s)
E0423 15:19:01.718263  6652 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
E0423 15:19:01.729264  6652 common.cpp:130] Cannot create Curand generator. Curand won't be available.
F0423 15:19:01.737263  6652 cudnn_conv_layer.cpp:52] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version
is insufficient for CUDA runtime version
*** Check failure stack trace: ***
openpose-1.3.0-win64-cpu-binaries>

cpu-binaries needs cuda？

**Comment by nanako-ut** [comment] 2018-04-25 05:47
1_extract_from_image.exe is same problem.

\openpose\openpose-1.3.0-win64-cpu-binaries> bin/1_extract_from_image.exe
OpenPose Library Tutorial - Example 1.
E0425 14:45:45.005944  8760 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
E0425 14:45:45.021556  8760 common.cpp:130] Cannot create Curand generator. Curand won't be available.
F0425 14:45:45.037195  8760 cudnn_conv_layer.cpp:52] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***

**Comment by gineshidalgo99** [comment] 2018-04-27 18:28
I'd try to debug the error, the problem is that my machine does have CUDA, so I can't detect this error on it.

As quick fix, could you try copying the CUDA DLLs from the GPU version for now? Does that work?

**Comment by gineshidalgo99** [comment] 2018-04-27 18:30
Also, include your system configuration as it appears in the github issue template, it'd also help me a bit. THanks!

**Comment by nanako-ut** [comment] 2018-04-29 12:15
I try copying 4 CUDA DLLs  from openpose-1.3.0-win64-gpu-binaries.zip

target folder is openpose-1.3.0-win64-cpu-binaries\bin
4 cuda dlls is 
　・cublas64_80.dll
　・cudart64_80.dll
　・cudnn64_5.dll
　・curand64_80.dll

but the same error occured.
openpose-1.3.0-win64-cpu-binaries> bin/OpenPoseDemo.exe --video examples/media/video.avi
Starting pose estimation demo.
Starting thread(s)
E0429 21:13:00.251471 14404 common.cpp:123] Cannot create Cublas handle. Cublas won't be available.
E0429 21:13:00.268482 14404 common.cpp:130] Cannot create Curand generator. Curand won't be available.
F0429 21:13:00.292528 14404 cudnn_conv_layer.cpp:52] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***

Also, I did install caffe CPU version(Visual Studio 2015, CPU only, Python 3.5).

**Comment by wadereye** [comment] 2018-05-01 04:35
I get the same error as you also.

**Comment by CharlesLiuyx** [comment] 2018-05-16 09:53
I got the same error
```
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
E0516 02:40:04.540171  9062 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0516 02:40:04.540477  9062 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0516 02:40:04.540578  9062 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f85948f25cd  google::LogMessage::Fail()
    @     0x7f85948f4433  google::LogMessage::SendToLog()
    @     0x7f85948f215b  google::LogMessage::Flush()
    @     0x7f85948f4e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8593e43cf2  caffe::Caffe::SetDevice()
    @     0x7f859618c30e  op::NetCaffe::initializationOnThread()
    @     0x7f85961b3bd8  op::addCaffeNetOnThread()
    @     0x7f85961b44f8  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f85961bc802  op::PoseExtractorNet::initializationOnThread()
    @     0x7f85961aff79  op::PoseExtractor::initializationOnThread()
    @     0x7f85961acd02  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f85961e6b60  op::SubThread<>::initializationOnThread()
    @     0x7f85961e8d6f  op::Thread<>::initializationOnThread()
    @     0x7f85961e8fc1  op::Thread<>::threadFunction()
    @     0x7f8596202f47  std::_Mem_fn_base<>::operator()<>()
    @     0x7f8596202edb  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7f8596202c8c  std::_Bind_simple<>::operator()()
    @     0x7f8596202a5c  std::thread::_Impl<>::_M_run()
    @     0x7f85957d7c80  (unknown)
    @     0x7f8594f296ba  start_thread
    @     0x7f859524641d  clone
    @              (nil)  (unknown)
[1]    9057 abort (core dumped)  ./build/examples/openpose/openpose.bin --image_dir examples/media/
```
I have cuda8 cuda9 cuda9.1 + cuDNN 7.1 6 5.1

And here is the version I got
``` 
> cat /usr/local/cuda/version.txt
CUDA Version 8.0.61
```
```
> cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```
```
Ubuntu 16.04 LTS
GTX 1080
```

**Comment by gjlroka** [comment] 2018-05-20 09:29
I get the same error.I try copying 4 CUDA DLLs but  the same error occured.
And according to  https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/556  I shouldn't need  to install CUDA and CUDNN for CPU.
I try to use it again without CUDA and CUDNN but the same error occured.

**Comment by gineshidalgo99** [comment] 2018-05-21 16:23
@nanako-ut 
@gjlroka 
@repoalpha 

Sorry for this, I didn't have a computer without Nvidia graphic so I couldn't debug this earlier. I'll push a fix during this week. I'll keep you posted. Thanks

**Comment by MaddalenaS** [comment] 2018-05-27 16:01
are there any news?

**Comment by soulslicer** [comment] 2018-05-27 17:37
it should be fixed this weekend

**Comment by gineshidalgo99** [comment] 2018-05-27 22:14
Hi all,
@soulslicer 
@nanako-ut
@gjlroka
@repoalpha
@MaddalenaS
@CharlesLiuyx
@wadereye
@gkm2709

Could you please try this provisional version? (done with the help of @soulslicer )
https://github.com/gineshidalgo99/openpose/tree/cpu

If it works, I will push it to OpenPose.

Again, we don't have a machine without CPU so we can't detect all the errors, but we compiled a CPU-only version of Caffe, so it should work and not request any CUDA file. Please, let me know if it works, and if it doesn't, please post here the error. Thanks!

**Comment by gineshidalgo99** [comment] 2018-05-28 01:31
@jaskarannagi19 If you did not get 3rdparty/windows/caffe_cpu, that means you are not using the right repository, or that you didn't follow the CPU instructions (basically set CPU_ONLY in CMake).

Let me know your output after you can see that caffe_cpu is there. Thanks!

**Comment by jaskarannagi19** [comment] 2018-05-28 01:38
@gineshidalgo99 
Followed the new link in above comment to the repo.
And did use CPU_ONLY in Cmake.

Ok I ReDo it and get back with that folder

**Comment by jaskarannagi19** [comment] 2018-05-28 02:39
@gineshidalgo99 
Something like this happened...Yes Now I have that cpu folder

[stacktrace.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/2043363/stacktrace.txt)

**Comment by gineshidalgo99** [comment] 2018-05-28 03:16
That's an out-of-memory (RAM) error (check FAQ and/or speed up hints). Reduce net_resolution to e.g. -1x80 to verify whether it runs properly other than the RAM memory issue.

**Comment by jaskarannagi19** [comment] 2018-05-28 07:13
Hey @gineshidalgo99 

Sorry for late reply but whenever I run this command it closes with not responding
.\build\x64\debug\OpenPoseDemo.exe --video examples\media\video.avi --net_resolution -1x80

Then I decided to attach VS debugger than I received following error. By the way how do you debug this app Sorry for dump question I am totally new to all these things. This never runs on VS debugging mode

Unhandled exception at 0x00007FF968721630 (vcruntime140d.dll) in OpenPoseDemo.exe: 0xC0000005: Access violation reading location 0x0000000000000000.
If there is a handler for this exception, the program may be safely continued.

**Comment by MaddalenaS** [comment] 2018-05-28 11:52
@gineshidalgo99  I also tried the version you uploaded, but I was not able to run it.

First I tried to run it through Visual Studio after compiled it, but I obtained a long list of line regarding the layers and then program crashed. So, I was not able to read the errors.

Then I tried to run it from the cmd, but this time I obtained a series of missing .dll and so the program has not even started.

**Comment by gineshidalgo99** [comment] 2018-05-28 12:29
Could you try the release version? In the debug one, caffe generates all that useless ouput for no reason. So it should only print the real error. Thanks! (Again, sorry but I don't have a non cuda machine to try it myself).

**Comment by MaddalenaS** [comment] 2018-05-28 12:36
I had already tried the Release version before. But the problems are equal:
-compiling with visual studio the program crashed
-runnung in the cmd I had .dll problems.

Using CMake I put CPU_ONLY and I disabled USE_CUDNN.

**Comment by gineshidalgo99** [comment] 2018-05-28 14:35
I am sorry for the error, and thanks for the feed-back. Then, we will need to wait until we can find a machine without CUDA on it. We can't do anything right now as we do not have this kind of hardware to replicate the issue. I will keep you posted.

The second solution is if you can compile Caffe for your Windows machine by yourselves, and then just indicate OpenPose where that Caffe is. The problem is Caffe not running for CPU_ONLY Windows machines.

**Comment by jaskarannagi19** [comment] 2018-05-28 14:45
@gineshidalgo99 
You can disable you card under device manager and booommm now you have a non cuda machine
OR 
you can use my machine on share screen

**Comment by gineshidalgo99** [comment] 2018-05-28 15:05
Our machines doesn't have integrated GPUs, making impossible to disable the Nvidia GPU (as I would lose my display). But we are looking for a machine without nvidia card, please, allow us 2-3 more days. Thanks!

**Comment by gineshidalgo99** [comment] 2018-05-28 16:18
Hi, we have just finally tried it in a non-Nvidia machine, and everything worked fine with no errors.

Thus, the fix has been added to official OpenPose (download the latest OpenPose + follow CPU instructions).

If you are still having issues, they are not an OpenPose bug anymore, but rather an installation or Visual Studio issue. Some hints (also available in the doc):

1. Remove your OpenPose folder and re-download it completely.
2. Run net_resolution -1x80 to debug that the issue is not a RAM out of memory error.
3. Copy all DLLs from 3rdparty/caffe/*.dll and 3rdparty/opencv/*.dll to the same folder where OpenPoseDemo.exe is located.

If you are still having issues:
1. Post all your system hardware configuration (when you click in creating a new github issue you will see the template).
2. Add screenshots of the error itself.

Thanks for your debugging help!

**Closed by gineshidalgo99** 2018-05-28 16:18 UTC
Labels: CPU only, bug/typo

**Comment by jaskarannagi19** [comment] 2018-05-28 17:21
Thanks @gineshidalgo99 
Its working from release build
No idea why it doesnt work in debug built.

**Comment by whyky** [comment] 2018-05-29 01:37
It works for me. Thank you.

**Comment by ssachio** [comment] 2018-06-06 07:32
Do you have a plan to upload Modified binaries?

**Comment by gineshidalgo99** [comment] 2018-06-06 17:56
With the next OpenPose version that should include many new interesting features. It should be released before June ends.

**Comment by rnditdev** [comment] 2018-06-14 18:16
Could you comment on the features to be released @gineshidalgo99? Thanks.

**Comment by MaddalenaS** [comment] 2018-06-20 20:51
Sorry if I report another problem, but I'm the only one to get this error
(error.png) always regarding the OpenPose version for CPU only. I'm not
able to solve it. Maybe you can help me.
Thank you.

Maddalena

Il giorno gio 14 giu 2018 alle ore 20:16 Rodolfo Bonnin <
notifications@github.com> ha scritto:

**Comment by aarti9** [comment] 2018-08-14 20:12
Hi @gineshidalgo99,
I am using the exe from the binaries but it gives me the error . Please advise. I need to run this urgently

C:\openpose-1.3.0-win64-gpu-binaries>bin\OpenPoseDemo.exe --image_dir examples\media\ --face --hand --write_images example\out
Starting pose estimation demo.

Error:
Cuda check failed (35 vs. 0): CUDA driver version is insufficient for CUDA runtime version

Coming from:
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():48
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\gpu\cuda.cpp:op::cudaCheck():37
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\gpu\cuda.cpp:op::getCudaGpuNumber():58
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\gpu\gpu.cpp:op::getGpuNumber():27
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\include\openpose/wrapper/wrapper.hpp:op::Wrapper<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> >,class std::shared_ptr<class op::Worker<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > >,class op::Queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::queue<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::deque<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > >,class std::allocator<class std::shared_ptr<class std::vector<struct op::Datum,class std::allocator<struct op::Datum> > > > > > > >::configure():941
