### ISSUE TITLE
Run time error with Turing GPU (Tesla T4)

### ISSUE THREAD

**Issue by wuchichung** [CMU-Perceptual-Computing-Lab/openpose#1232] opened 2019-05-22 11:10 UTC
To solve problem,

change /openpose/3rdparty/caffe/cmake/Cuda.cmake line 7:

from : 
     set(Caffe_known_gpu_archs "30 35 50 52 60 61")
to :
     set(Caffe_known_gpu_archs "30 35 50 52 60 61 75")

**Comment by gineshidalgo99** [comment] 2019-05-22 13:50
That is a bit weird, OpenPose will use the native configuration by default. Are you adding any special flag on CMake regarding CUDA when configuring it? If you use the default OpenPose setting, it should compile Turing GPUs as well (tested on my machines).

(I will keep answering even though I am closing it as no followup question is added).

**Closed by gineshidalgo99** 2019-05-22 13:51 UTC

**Comment by wuchichung** [comment] 2019-05-23 01:57
My cmake command:

cmake -DOpenCV_INCLUDE_DIRS=/opt/opencv/build/OpenCVConfig.cmake \
          -DDOWNLOAD_BODY_25_MODEL=OFF\
          -DDOWNLOAD_FACE_MODEL=OFF\
          -DDOWNLOAD_HAND_MODEL=OFF\
          -DBUILD_EXAMPLES=OFF\
          -DBUILD_PYTHON=ON\
          -DPYTHON_EXECUTABLE=/usr/bin/python2\
          -DPYTHON_LIBRARY=/usr/lib/*-linux-gnu/libpython2.7.so\
          ..

**Comment by gineshidalgo99** [comment] 2019-05-24 13:01
I cannot reproduce that error, sorry! But I will add your fix to the doc/faq.md in case somebody else faces it. Thanks!
