### ISSUE TITLE
【Ubuntu Execution error】Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by postgraduater** [CMU-Perceptual-Computing-Lab/openpose#357] opened 2017-12-20 12:08 UTC
### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi

### OpenPose Output (if any)
Starting pose estimation demo.
Auto-detecting GPUs... Detected 7 GPU(s), using them all.
Starting thread(s)
F1220 862416 12506 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7fd5b899d5cd  google::LogMessage::Fail()
    @     0x7fd5b899f433  google::LogMessage::SendToLog()
    @     0x7fd5b899d15b  google::LogMessage::Flush()
    @     0x7fd5b899fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd5b907dc76  caffe::CuDNNReLULayer<>::LayerSetUp()
    @     0x7fd5b90fe203  caffe::Net<>::Init()
    @     0x7fd5b9101040  caffe::Net<>::Net()
    @     0x7fd5ba831dd8  op::NetCaffe::initializationOnThread()
    @     0x7fd5ba7a887b  op::addCaffeNetOnThread()
    @     0x7fd5ba7a933c  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fd5ba7a1570  op::PoseExtractor::initializationOnThread()
    @     0x7fd5ba70a921  op::SubThread<>::initializationOnThread()
    @     0x7fd5ba70af10  op::Thread<>::initializationOnThread()
    @     0x7fd5ba70fd7d  op::Thread<>::threadFunction()
    @     0x7fd5ba168c80  (unknown)
    @     0x7fd5b72e36ba  start_thread
    @     0x7fd5b9bd73dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

### Type of Issue
- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**Installation mode**: manual Makefile installation (Ubuntu); 
**CUDA version** (cuda-8.0):
**cuDNN version**:（cuDNN 6）
**GPU model** (`nvidia-smi` in Ubuntu):
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 52%   82C    P2   237W / 250W |  11587MiB / 12207MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   40C    P0    69W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:08:00.0 Off |                  N/A |
| 41%   81C    P2   238W / 250W |  10607MiB / 12207MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:09:00.0 Off |                  N/A |
| 48%   82C    P2   235W / 250W |  11225MiB / 12207MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 40%   81C    P2   221W / 250W |  11715MiB / 12207MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  Off  | 00000000:87:00.0 Off |                  N/A |
| 22%   35C    P0    71W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  Off  | 00000000:88:00.0 Off |                  N/A |
| 22%   36C    P0    67W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2678      C   python                                     11574MiB |
|    2      8911      C   python                                     10596MiB |
|    3     10510      C   python                                     11206MiB |
|    4     30108      C   python                                     11704MiB |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);

### Executed Command (if any)
./build/examples/openpose/openpose.bin --video examples/media/video.avi

### OpenPose Output (if any)
Starting pose estimation demo.
Auto-detecting GPUs... Detected 7 GPU(s), using them all.
Starting thread(s)
F1220 862416 12506 cudnn_relu_layer.cpp:13] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7fd5b899d5cd  google::LogMessage::Fail()
    @     0x7fd5b899f433  google::LogMessage::SendToLog()
    @     0x7fd5b899d15b  google::LogMessage::Flush()
    @     0x7fd5b899fe1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd5b907dc76  caffe::CuDNNReLULayer<>::LayerSetUp()
    @     0x7fd5b90fe203  caffe::Net<>::Init()
    @     0x7fd5b9101040  caffe::Net<>::Net()
    @     0x7fd5ba831dd8  op::NetCaffe::initializationOnThread()
    @     0x7fd5ba7a887b  op::addCaffeNetOnThread()
    @     0x7fd5ba7a933c  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fd5ba7a1570  op::PoseExtractor::initializationOnThread()
    @     0x7fd5ba70a921  op::SubThread<>::initializationOnThread()
    @     0x7fd5ba70af10  op::Thread<>::initializationOnThread()
    @     0x7fd5ba70fd7d  op::Thread<>::threadFunction()
    @     0x7fd5ba168c80  (unknown)
    @     0x7fd5b72e36ba  start_thread
    @     0x7fd5b9bd73dd  clone
    @              (nil)  (unknown)
Aborted (core dumped)

### Type of Issue
- Execution error

### Your System Configuration
**Operating system** (`lsb_release -a` in Ubuntu):
**Installation mode**: manual Makefile installation (Ubuntu); 
**CUDA version** (cuda-8.0):
**cuDNN version**:（cuDNN 6）
**GPU model** (`nvidia-smi` in Ubuntu):
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.98                 Driver Version: 384.98                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX TIT...  Off  | 00000000:04:00.0 Off |                  N/A |
| 52%   82C    P2   237W / 250W |  11587MiB / 12207MiB |     98%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX TIT...  Off  | 00000000:05:00.0 Off |                  N/A |
| 22%   40C    P0    69W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX TIT...  Off  | 00000000:08:00.0 Off |                  N/A |
| 41%   81C    P2   238W / 250W |  10607MiB / 12207MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX TIT...  Off  | 00000000:09:00.0 Off |                  N/A |
| 48%   82C    P2   235W / 250W |  11225MiB / 12207MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX TIT...  Off  | 00000000:83:00.0 Off |                  N/A |
| 40%   81C    P2   221W / 250W |  11715MiB / 12207MiB |     96%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX TIT...  Off  | 00000000:87:00.0 Off |                  N/A |
| 22%   35C    P0    71W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX TIT...  Off  | 00000000:88:00.0 Off |                  N/A |
| 22%   36C    P0    67W / 250W |      0MiB / 12207MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      2678      C   python                                     11574MiB |
|    2      8911      C   python                                     10596MiB |
|    3     10510      C   python                                     11206MiB |
|    4     30108      C   python                                     11704MiB |
+-----------------------------------------------------------------------------+

**Caffe version**: Default from OpenPose
**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu);

**Comment by gineshidalgo99** [comment] 2017-12-20 15:13
From: https://github.com/tensorflow/tensorflow/issues/8879#issuecomment-290973405

> Looks like previous instances of the same error messages were usually cuDNN version mismatches.
> Maybe we have a cuDNN patch version mismatch.

So please, try re-installing cuDNN making sure is for the right CUDA version and reboot the machine. This is not an OpenPose issue so I must close it, you will find much better support online otherwise, as it's a cuDNN problem. Thanks!

**Closed by gineshidalgo99** 2017-12-20 15:13 UTC
Labels: 3rd party

**Comment by mengqingmeng** [comment] 2018-01-23 13:38
run 'nvidia-smi' and try again

**Comment by bryancresswell** [comment] 2018-04-13 05:09
This is not working for me. Does anyone have any idea?

**Comment by Mia077** [comment] 2021-03-03 13:29
> This is not working for me. Does anyone have any idea?

Hi, have you ever solved this problem? I have the same question now.

Thanks a lot!

**Comment by syguan96** [comment] 2022-02-23 13:21
The error is caused by OOM.
