### ISSUE TITLE
[Windows] Memory usage increases and FPS decreases

### ISSUE THREAD

**Issue by FreshlyBrewedCode** [CMU-Perceptual-Computing-Lab/openpose#1811] opened 2020-12-30 14:40 UTC
### Issue Summary
I am running the precompiled windows OP demo on the COCO val2017 images (5000 images) using the deafult body_25 model. Using `--net_resolution "-1x368"` I get ~20fps and total memory usage of ~7gb (RTX 3070 8gb). However, after about 400 images memory usage increases by ~1gb and FPS decreases to ~10fps. After another 400 images it happens again and memory is maxed out at almost 8gb and FPS drops down to ~5fps. 
Here is a screenshot of a hardware monitor plot:
![image](https://user-images.githubusercontent.com/11772241/103355271-23c7e580-4aae-11eb-8405-1a0f005d1c96.png)
The behavior is visible in the third plot (memory usage).

I did run the same test using ``--net_resolution "-1x256"` and got the same behavior with less total memory usage:
![image](https://user-images.githubusercontent.com/11772241/103355576-dac46100-4aae-11eb-898d-5422e64a2dd0.png)
In the plot you can see that the memory increases several times (always after about 400 images). However, using the decreased net resolution the FPS stays consistant at ~30fps even after the memory increase.

Is this expected behavior and are there any workarounds other than lowering the net resolution? My goal is to validate the model accuracy using the COCO json output.

### Executed Command (if any)
```powershell
& $OpenPoseDemoExe --model_folder $modelFolder --prototxt_path $prototxt_path --caffemodel_path $modelPath `
    --image_dir $imageDir --render_pose 1 --display 1 --cli_verbose 0.2 --write_coco_json $tempJson --num_gpu -1  `
    --write_coco_json_variants 3 --net_resolution "-1x256" --scale_number 1
```
I get similar behavior by running with `--render_pose 0 --display 0`. 

### OpenPose Output (if any)
```
Starting OpenPose demo...
Configuring OpenPose...
Starting thread(s)...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Processing frame 1/5000...
Processing frame 1000/5000...
Processing frame 2000/5000...
Processing frame 3000/5000...
Processing frame 4000/5000...
Processing frame 5000/5000...
OpenPose demo successfully finished. Total time: 158.239057 seconds.
```
*Total time for `--net_resolution "-1x256"`. For `--net_resolution "-1x368"` total time is ~26min due to the low FPS after ~800 images.

### Type of Issue
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared): *see above, no errors*

2. **OpenPose version**: [GitHub release v1.7.0](https://github.com/CMU-Perceptual-Computing-Lab/openpose/releases/tag/v1.7.0)

3. **General configuration**:
    - **Installation mode**: Precompiled release
    - **Operating system**: Windows 10 Pro
    - **Operating system version**: 2004 (Build: 20279.1)
    - **Release or Debug mode**?: release

4. **Non-default settings**:
    - **3-D Reconstruction module added**?: no
    - Any other custom CMake configuration with respect to the default version?: no

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **OpenCV version**: OpenPose default

6. If **GPU mode** issue:
    - **CUDA version**: OpenPose default
    - **cuDNN version**: OpenPose default
    - **GPU model**: GeForce RTX 3070 8 GB

7. If **CPU-only mode** issue:
    - **CPU brand & model**: AMD Ryzen 5 2600 Six-Core Processor 3.40 GHz 
    - Total **RAM memory** available: 16 GB

9. If **Windows** system:
    - Portable demo

10. If **speed performance** issue:
    If more accurate metrics are required I can run some tests with `PROFILER_ENABLED`.

**Comment by gineshidalgo99** [comment] 2021-01-11 01:04
Hi! 

Short answer, you should use --net_resolution "-656x368" to keep the memory and speed constant (please, confirm this is the case to make sure there are no bugs in OpenPose in your machine!), but it would harm the accuracy a bit (very bit) and affect the speed a bit too.

Long answer, using the -1 in net_resolution means adapting the OpenPose network to the best aspect ratio for each frame. Meaning, if you switch from horizontal to vertical frames, the network increases its size a lot. So using the -1 will get the maximum accuracy-speed (not adding black padding to images to adapt to the usual 16/9 aspect ratio).

Closing this as solved, but let me know if my answers do not work in your case and will reply! :)

Very low level details (optional to be read!)
Given all the out of memory errors people have reported, and that are actually caused by this -1 resolution when applied to vertical images, I am gonna update the default behavior of OpenPose to add a new flag called:
net_resolution_automatic_behavior which is an integer value (0, 1, 2), where:
- 0 means using -1x368 and adapting (although memory might do what you are saying). This gives the maximum accuracy assuming you have enough memory (which is variable depending on your image aspect ratios).
- -1 means using the 656 as the maximum possible value, but still being variable. This will keep memory fixed, the same accuracy than a fixed 656x368, but maximize the speed for images with smaller (but not bigger ones)
- And any other value as a maximum ratio. Eg if using 2 will mean adaptive memory but growing to a maximum of 2x656. This is an advance setting for those knowing what they are doing but just as a way to avoid out of memory for very vertical images.

**Closed by gineshidalgo99** 2021-01-11 01:04 UTC
